### ISSUE TITLE
👋 Examples/Demo App

### ISSUE THREAD

**Issue by baksha97** [aumChauhan/MaterialUIKit#1]
An examples app would be a great addition to the project.
- quickly review what the package can offer
- quickly test if allows certain levels of customization
- allow for more images/screenshots in README.md

**Comment by aumChauhan** [comment]
Thank you for the suggestion! 
Adding an examples app is indeed a great idea.
In the meantime, users can check out the [Wiki page](https://github.com/aumChauhan/MaterialUIKit/wiki) for some examples and previews until the demo project is ready.

**Comment by aumChauhan** [comment]
I've added a sample project to the repository: [MaterialUIKit Sample Project](https://github.com/aumChauhan/MaterialUIKit_SampleProject). For more examples and previews, check the wiki.
